name: Parse csv's into JSON to be consumed by the visualization

on:
  push:
    branches:
      - main

jobs:
  Build-JSON:
    runs-on: ubuntu-18.04
    steps:
      - name: "Checkout the Repository"
        uses: actions/checkout@v2

      - name: "Setup Python"
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: "Download required Python packages"
        run: pip install -r requirements.txt

      - name: "Build the JSON file"
        run: to_json.py

      - name: "Merge into Prod"
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
    
          git add --all
          
          git commit -m "Update the JSON with new data"
          
          git push